# Generated by Django 5.2.12 on 2026-09-29 06:02

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact inquiry',
                'verbose_name_plural': 'Contact inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('section', models.CharField(choices=[('about', 'About'), ('team', 'Our Team'), ('services', 'Services'), ('notices', 'Notices'), ('media', 'Media'), ('contact', 'Contact Us')], max_length=20, unique=True)),
                ('introduction', models.TextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Website section',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceItemPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('summary', models.TextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('availability', models.CharField(choices=[('current', 'Current service'), ('confirm', 'Availability to confirm')], default='current', max_length=20)),
                ('icon_name', models.CharField(blank=True, help_text='Optional short icon key, for example medicines or clinic.', max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_eyebrow', models.CharField(default='Healthcare access across Nepal', max_length=120)),
                ('hero_heading', models.CharField(default='Essential medicine. Closer to everyone.', max_length=180)),
                ('hero_intro', models.TextField(default='MSMT Nepal works to strengthen access to essential medicines and healthcare support through dependable supply and community-focused services.')),
                ('founding_year', models.CharField(default='2004', max_length=12)),
                ('services_heading', models.CharField(default='Services that support healthier communities', max_length=160)),
                ('services_intro', models.CharField(default='Reliable medicine supply and practical care, designed around community needs.', max_length=240)),
                ('impact_heading', models.CharField(default='Better access, stronger health systems', max_length=140)),
                ('impact_text', models.TextField(default='MSMT Nepal is a professional, socially driven trust established in 2004 to help make quality medicines and healthcare more accessible, especially for poor and vulnerable communities.')),
                ('objective_heading', models.CharField(default='Reliable and affordable care', max_length=140)),
                ('objective_text', models.TextField(default='Ensure continuous access to essential medicines and medical equipment, strengthen sustainable supply systems, build healthcare capacity, and reinvest surpluses in service improvement.')),
                ('service_support_heading', models.CharField(default='Support from supply to community care', max_length=140)),
                ('service_support_text', models.TextField(default='Medicine and medical goods supply, doorstep medicine delivery, community clinic care, annual health camps, humanitarian response, and professional training for healthcare providers.')),
                ('approach_heading', models.CharField(default='Quality and reliability', max_length=140)),
                ('approach_text', models.TextField(default='MSMT Nepal brings together medical, pharmaceutical and management professionals to support dependable medicine supply and stronger healthcare services.')),
                ('approach_point_one', models.CharField(default='Working with health providers and communities', max_length=140)),
                ('approach_point_two', models.CharField(default='Supporting sustainable medicine supply', max_length=140)),
                ('approach_point_three', models.CharField(default='Building skills through training and collaboration', max_length=140)),
                ('media_heading', models.CharField(default='Stories, updates and resources', max_length=140)),
                ('media_intro', models.TextField(default='Contact MSMT Nepal to learn more about its services and work with communities.')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Homepage',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MediaStoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('summary', models.TextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NoticePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('summary', models.TextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('published_on', models.DateField(default=django.utils.timezone.localdate)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='MSMT Nepal', max_length=120)),
                ('tagline', models.CharField(default='Working to improve access to essential medicines and healthcare services in Nepal.', max_length=180)),
                ('address', models.CharField(default='Chakupat, Lalitpur-11, Nepal', max_length=240)),
                ('email', models.EmailField(default='msmt.ngo.nepal@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+977 9768533691', max_length=40)),
                ('secondary_phone', models.CharField(blank=True, max_length=40)),
                ('map_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('footer_note', models.CharField(default='Information on this site is for general organizational purposes.', max_length=220)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Website contact and footer',
            },
        ),
        migrations.CreateModel(
            name='TeamMemberPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('summary', models.TextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=140)),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
