# Generated by Django 5.2.12 on 2026-10-01 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='impact_stat_four_label',
            field=models.CharField(default='Quality management certification', max_length=90),
        ),
        migrations.AddField(
            model_name='homepage',
            name='impact_stat_four_value',
            field=models.CharField(default='ISO 9001:2015', max_length=32),
        ),
        migrations.AddField(
            model_name='homepage',
            name='impact_stat_three_label',
            field=models.CharField(default='Districts reached', max_length=90),
        ),
        migrations.AddField(
            model_name='homepage',
            name='impact_stat_three_value',
            field=models.CharField(default='70+', max_length=32),
        ),
        migrations.AddField(
            model_name='homepage',
            name='impact_stat_two_label',
            field=models.CharField(default='Partner hospitals and community clinics', max_length=90),
        ),
        migrations.AddField(
            model_name='homepage',
            name='impact_stat_two_value',
            field=models.CharField(default='50+', max_length=32),
        ),
        migrations.AddField(
            model_name='serviceitempage',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
