# Generated by Django 5.2.12 on 2026-10-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepage_impact_stat_four_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, default='https://maps.google.com/maps?q=27.6821339,85.3264003&z=16&output=embed'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='impact_stat_four_label',
            field=models.CharField(default='Districts reached', max_length=90),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='impact_stat_four_value',
            field=models.CharField(default='70+', max_length=32),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='impact_stat_three_label',
            field=models.CharField(default='Partner hospitals and community clinics', max_length=90),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='impact_stat_three_value',
            field=models.CharField(default='50+', max_length=32),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='impact_stat_two_label',
            field=models.CharField(default='Years of services', max_length=90),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='impact_stat_two_value',
            field=models.CharField(default='20+', max_length=32),
        ),
    ]
